### Imports

In [1]:
import pandas as pd

### Filtering by the most influential features + avoiding redundancy

In [15]:
barttorvik = pd.read_csv("Dataset/Barttorvik Away-Neutral.csv").sort_values(by = ['SEED', 'YEAR'], ascending = [True, False])

barttorvik_features = ['TEAM','YEAR', 'TEAM NO', 'SEED', 'BADJ O', 'BADJ D', 'EFG%','EFG%D', 'FTR', 'FTRD', 'FT%', 'TOV%', 'TOV%D', 'OREB%', 'DREB%', 
'2PT%', '2PT%D', '3PT%', '3PT%D', 'BLK%', 'BLKED%', 'AST%', 'OP AST%', '2PTR', '3PTR', '2PTRD', '3PTRD', 'BADJ T', 'EFF HGT', 'EXP', 'TALENT', 'PPPO', 'PPPD', 'ELITE SOS', 'WAB']

barttorvik = barttorvik[barttorvik_features]
barttorvik.columns

Index(['TEAM', 'YEAR', 'TEAM NO', 'SEED', 'BADJ O', 'BADJ D', 'EFG%', 'EFG%D',
       'FTR', 'FTRD', 'FT%', 'TOV%', 'TOV%D', 'OREB%', 'DREB%', '2PT%',
       '2PT%D', '3PT%', '3PT%D', 'BLK%', 'BLKED%', 'AST%', 'OP AST%', '2PTR',
       '3PTR', '2PTRD', '3PTRD', 'BADJ T', 'EFF HGT', 'EXP', 'TALENT', 'PPPO',
       'PPPD', 'ELITE SOS', 'WAB'],
      dtype='object')

In [3]:
evan_miya = pd.read_csv("Dataset/EvanMiya.csv").sort_values(by = ['SEED', 'YEAR'], ascending = [True, False])

evan_miya_features = ['TEAM', 'YEAR', 'TEAM NO', 'O RATE', 'D RATE','OPPONENT ADJUST', 'PACE ADJUST', 'TRUE TEMPO']

evan_miya = evan_miya[evan_miya_features]
evan_miya

,TEAM,YEAR,TEAM NO,O RATE,D RATE,OPPONENT ADJUST,PACE ADJUST,TRUE TEMPO
6,Auburn,2025,1141,18.345438,12.090102,-10.808910,75.564620,69.449925
15,Duke,2025,1132,20.629884,15.188260,10.622804,28.211637,67.422555
16,Florida,2025,1131,18.648040,14.191978,99.009901,43.853550,71.319010
21,Houston,2025,1126,15.624891,18.508179,-15.419621,-3.573542,63.501250
80,Connecticut,2024,1067,19.151259,13.722032,87.919098,45.225030,66.376877
...,...,...,...,...,...,...,...,...
775,Liberty,2013,372,-2.787231,-7.039690,23.414119,-0.515103,66.357415
776,LIU Brooklyn,2013,371,8.881854,-7.603833,14.067136,11.326890,69.215782
791,North Carolina A&T,2013,356,-10.701206,2.872890,6.904985,3.847731,67.164585
805,Southern,2013,342,-6.183152,2.715103,-17.534152,12.939880,65.994201
813,Western Kentucky,2013,334,-1.974127,-0.153605,-13.464579,24.048115,66.515957

In [4]:
kenpom = pd.read_csv("Dataset/KenPom Barttorvik.csv").sort_values(by = ['SEED', 'YEAR'], ascending = [True, False])
# Note: O, D, T very similar to barrtorvik - essentially same metric different derived using slightly different methods
kenpom_features = ['TEAM', 'YEAR', 'TEAM NO', 'KADJ O', 'KADJ D', 'KADJ T']  

kenpom = kenpom[kenpom_features]
kenpom

                        TEAM  YEAR  TEAM NO    KADJ O    KADJ D   KADJ T
6                     Auburn  2025     1141  128.5050   93.4663  67.6684
15                      Duke  2025     1132  127.9990   89.8470  65.8030
16                   Florida  2025     1131  127.9380   92.1126  69.5912
21                   Houston  2025     1126  123.2690   87.8253  61.5016
80               Connecticut  2024     1067  126.6080   94.3949  64.4543
...                      ...   ...      ...       ...       ...      ...
1094              Coppin St.  2008       53   92.4179  106.6580  62.2413
1114  Mississippi Valley St.  2008       33   92.1127  107.0800  62.3905
1115        Mount St. Mary's  2008       32   99.0167  100.0580  65.2309
1122            Portland St.  2008       25  108.4110  102.5740  65.7791
1138            UT Arlington  2008        9  101.1400  103.1380  68.0296

[1147 rows x 6 columns]

In [5]:
rppf = pd.read_csv("Dataset/RPPF Ratings.csv").sort_values(by = ['SEED', 'YEAR'], ascending = [True, False])

rppf_features = ['TEAM', 'YEAR', 'TEAM NO', 'RADJ O', 'RADJ D', 'R PACE', 'R SOS', 'STROE', 'STRDE']

rppf = rppf[rppf_features]
rppf

,TEAM,YEAR,TEAM NO,RADJ O,RADJ D,R PACE,R SOS,STROE,STRDE
6,Auburn,2025,1141,129.1,93.2,67.6,0.8049,113.57,82.51
15,Duke,2025,1132,128.9,89.7,65.8,0.7273,109.01,80.16
16,Florida,2025,1131,130.0,92.5,69.7,0.7543,117.14,78.92
21,Houston,2025,1126,123.2,87.3,61.5,0.7660,94.77,82.45
80,Connecticut,2024,1067,127.1,93.8,64.5,0.7260,106.18,87.29
...,...,...,...,...,...,...,...,...,...
842,LIU Brooklyn,2012,305,109.3,109.3,73.0,0.5207,88.59,93.96
850,Mississippi Valley St.,2012,297,98.1,106.2,68.1,0.4402,68.61,97.37
873,UNC Asheville,2012,274,109.8,105.1,67.9,0.5184,84.90,96.45
877,Vermont,2012,270,104.1,100.1,61.6,0.4900,69.53,99.82
880,Western Kentucky,2012,267,98.7,101.4,67.1,0.6077,66.41,93.54

In [6]:
shooting_splits = pd.read_csv("Dataset/Shooting Splits.csv").sort_values(by = ['YEAR'], ascending = [False])

shooting_splits_features = ['TEAM', 'YEAR', 'TEAM NO', 'CLOSE TWOS FG%', 'CLOSE TWOS SHARE', 'CLOSE TWOS FG%D', 
'CLOSE TWOS D SHARE', 'FARTHER TWOS FG%', 'FARTHER TWOS SHARE', 'FARTHER TWOS FG%D', 'FARTHER TWOS D SHARE', 'THREES FG%',
'THREES SHARE', 'THREES FG%D', 'THREES D SHARE']

shooting_splits = shooting_splits[shooting_splits_features]
shooting_splits

,TEAM,YEAR,TEAM NO,CLOSE TWOS FG%,CLOSE TWOS SHARE,CLOSE TWOS FG%D,CLOSE TWOS D SHARE,FARTHER TWOS FG%,FARTHER TWOS SHARE,FARTHER TWOS FG%D,FARTHER TWOS D SHARE,THREES FG%,THREES SHARE,THREES FG%D,THREES D SHARE
0,Akron,2025,1147,61.8,38.2,55.3,41.7,42.0,16.5,41.0,20.3,36.6,45.4,31.9,38.0
1,Alabama,2025,1146,62.4,42.0,56.8,34.5,50.0,11.8,39.6,30.4,35.0,46.2,30.8,35.1
2,Alabama St.,2025,1145,53.1,36.6,57.7,39.0,31.5,20.5,37.4,21.6,32.9,42.9,33.4,39.5
3,American,2025,1144,58.5,33.8,62.2,40.2,39.4,21.4,37.9,24.2,35.1,44.8,33.6,35.7
4,Arizona,2025,1143,65.9,39.8,55.8,29.5,38.4,25.6,38.5,28.6,32.4,34.6,33.6,41.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1012,West Virginia,2010,135,62.7,29.6,57.8,34.6,35.6,35.6,33.9,33.2,33.8,34.7,32.4,32.2
1013,Winthrop,2010,134,60.9,23.6,65.2,27.1,34.0,50.3,32.2,37.6,25.7,26.1,30.0,35.3
1014,Wisconsin,2010,133,61.0,25.0,52.3,28.2,42.3,35.5,40.9,46.4,35.7,39.4,34.3,25.4
1015,Wofford,2010,132,55.1,46.1,58.9,35.4,33.5,23.3,34.3,34.2,35.1,30.6,30.9,30.4
1016,Xavier,2010,131,62.0,37.3,61.2,31.9,35.7,30.8,32.8,36.8,37.7,31.9,29.8,31.2

### Merging datasets into one

In [7]:
df = barttorvik.merge(evan_miya, on = ['TEAM NO', 'TEAM', 'YEAR'], how = 'inner')
df = df.merge(kenpom, on = ['TEAM NO', 'TEAM', 'YEAR'], how = 'inner')
df = df.merge(rppf, on = ['TEAM NO', 'TEAM', 'YEAR'], how = 'inner')
df = df.merge(shooting_splits, on = ['TEAM NO', 'TEAM', 'YEAR'], how = 'inner')
df

,TEAM,YEAR,TEAM NO,SEED,BADJ O,BADJ D,EFG%,EFG%D,FTR,FTRD,...,CLOSE TWOS FG%D,CLOSE TWOS D SHARE,FARTHER TWOS FG%,FARTHER TWOS SHARE,FARTHER TWOS FG%D,FARTHER TWOS D SHARE,THREES FG%,THREES SHARE,THREES FG%D,THREES D SHARE
0,Auburn,2025,1141,1,133.1,96.3,55.0,48.6,31.1,43.0,...,54.8,41.5,44.9,22.2,33.8,23.8,36.8,40.6,29.2,34.8
1,Duke,2025,1132,1,126.3,90.8,56.9,46.5,30.4,28.6,...,53.8,31.8,44.4,15.6,32.5,30.2,37.7,45.4,30.9,37.9
2,Florida,2025,1131,1,127.0,96.2,53.6,48.6,33.6,34.0,...,54.4,36.9,38.1,18.3,33.4,25.6,35.1,43.5,30.2,37.5
3,Houston,2025,1126,1,122.6,89.4,50.2,45.7,30.1,36.2,...,53.8,32.8,40.3,40.9,30.4,24.2,39.8,34.5,30.9,43.1
4,Connecticut,2024,1067,1,128.5,97.3,56.7,48.4,30.9,33.8,...,49.3,38.3,40.6,18.4,36.2,28.5,36.7,40.9,31.9,33.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,Liberty,2013,372,16,98.6,108.7,47.5,47.9,38.5,40.0,...,57.5,35.8,33.9,29.6,38.3,31.0,37.0,34.6,30.9,33.1
812,LIU Brooklyn,2013,371,16,109.4,113.3,54.3,55.6,44.0,31.9,...,61.1,38.9,32.7,19.2,38.3,30.2,38.1,33.9,37.2,30.9
813,North Carolina A&T,2013,356,16,89.8,95.5,44.7,45.0,43.6,44.0,...,53.5,35.0,30.4,27.1,30.5,27.0,30.7,36.9,32.1,38.0
814,Southern,2013,342,16,94.7,98.1,48.4,44.1,42.7,38.5,...,52.5,30.0,34.1,37.3,31.6,39.6,36.7,34.9,30.1,30.4
815,Western Kentucky,2013,334,16,98.8,100.9,48.1,48.9,34.8,41.3,...,60.9,30.6,36.2,30.4,36.8,38.0,32.7,36.2,32.4,31.3

In [8]:
print(df.columns)

Index(['TEAM', 'YEAR', 'TEAM NO', 'SEED', 'BADJ O', 'BADJ D', 'EFG%', 'EFG%D',
       'FTR', 'FTRD', 'FT%', 'TOV%', 'TOV%D', 'OREB%', 'DREB%', '2PT%',
       '2PT%D', '3PT%', '3PT%D', 'BLK%', 'BLKED%', 'AST%', 'OP AST%', '2PTR',
       '3PTR', '2PTRD', '3PTRD', 'BADJ T', 'EFF HGT', 'EXP', 'TALENT', 'PPPO',
       'PPPD', 'ELITE SOS', 'WAB', 'O RATE', 'D RATE', 'OPPONENT ADJUST',
       'PACE ADJUST', 'TRUE TEMPO', 'KADJ O', 'KADJ D', 'KADJ T', 'RADJ O',
       'RADJ D', 'R PACE', 'R SOS', 'STROE', 'STRDE', 'CLOSE TWOS FG%',
       'CLOSE TWOS SHARE', 'CLOSE TWOS FG%D', 'CLOSE TWOS D SHARE',
       'FARTHER TWOS FG%', 'FARTHER TWOS SHARE', 'FARTHER TWOS FG%D',
       'FARTHER TWOS D SHARE', 'THREES FG%', 'THREES SHARE', 'THREES FG%D',
       'THREES D SHARE'],
      dtype='object')

In [14]:
mm_team_features = df.groupby(['TEAM', 'YEAR']).mean()
mm_team_features

                        TEAM NO  SEED  BADJ O  BADJ D  EFG%  EFG%D   FTR  \
TEAM              YEAR
Abilene Christian 2019    807.0  15.0   100.9    99.7  50.7   49.8  32.1
                  2021    875.0  14.0    99.8    95.4  52.4   47.1  33.0
Akron             2013    399.0  12.0   106.0    95.4  50.7   44.6  38.9
                  2022    943.0  13.0   105.1    97.7  52.0   46.8  36.5
                  2024   1079.0  14.0   105.0   101.9  51.5   49.3  31.1
...                         ...   ...     ...     ...   ...    ...   ...
Yale              2016    536.0  12.0   106.5    95.5  50.7   46.4  36.7
                  2019    740.0  14.0   107.0    99.3  54.3   47.1  28.5
                  2022    876.0  14.0    98.6    96.9  48.8   48.8  31.1
                  2024   1012.0  13.0   109.4    99.3  50.4   49.2  27.1
                  2025   1080.0  13.0   113.8   106.0  55.1   50.7  33.1

                        FTRD   FT%  TOV%  ...  CLOSE TWOS FG%D  \
TEAM              YEAR                    ...
Abilene Christian 2019  36.8  71.4  16.6  ...             61.7
                  2021  41.0  65.2  20.0  ...             56.0
Akron             2013  41.6  62.0  20.9  ...             46.2
                  2022  26.1  70.8  17.7  ...             54.0
                  2024  30.7  71.7  18.2  ...             58.0
...                      ...   ...   ...  ...              ...
Yale              2016  33.3  65.7  20.4  ...             51.4
                  2019  35.7  69.9  19.9  ...             58.4
                  2022  25.6  69.5  19.1  ...             60.8
                  2024  30.5  71.4  14.1  ...             58.7
                  2025  30.8  72.4  15.2  ...             55.0

                        CLOSE TWOS D SHARE  FARTHER TWOS FG%  \
TEAM              YEAR
Abilene Christian 2019                32.9              36.4
                  2021                35.1              34.4
Akron             2013                46.8              37.2
                  2022                36.1              42.3
                  2024                37.7              43.8
...                                    ...               ...
Yale              2016                34.6              42.6
                  2019                35.9              38.6
                  2022                34.5              41.9
                  2024                32.1              42.4
                  2025                33.5              44.9

                        FARTHER TWOS SHARE  FARTHER TWOS FG%D  \
TEAM              YEAR
Abilene Christian 2019                31.5               38.1
                  2021                21.2               36.2
Akron             2013                19.8               35.9
                  2022                28.4               39.0
                  2024                24.6               39.9
...                                    ...                ...
Yale              2016                32.2               38.9
                  2019                24.8               33.2
                  2022                27.2               37.4
                  2024                25.8               36.8
                  2025                24.2               33.3

                        FARTHER TWOS D SHARE  THREES FG%  THREES SHARE  \
TEAM              YEAR
Abilene Christian 2019                  33.9        37.7          34.5
                  2021                  30.5        36.4          36.0
Akron             2013                  23.8        32.8          36.4
                  2022                  28.6        35.3          41.4
                  2024                  25.6        32.0          41.5
...                                      ...         ...           ...
Yale              2016                  31.1        36.0          31.1
                  2019                  26.2        36.5          35.3
                  2022                  24.3        32.6          36.0
                  2024                  26.6        34.6          35.3
                  2025                  18.5        38.5          32.0

                        THREES FG%D  THREES D SHARE
TEAM              YEAR
Abilene Christian 2019         33.3            33.1
                  2021         29.8            34.4
Akron             2013         32.8            29.4
                  2022         34.9            35.3
                  2024         30.0            36.8
...                             ...             ...
Yale              2016         32.7            34.3
                  2019         31.0            37.8
                  2022         30.5            41.2
                  2024         34.0            41.4
                  2025         33.7            48.0

[816 rows x 59 columns]